FROM node:20-alpine

WORKDIR /repo

COPY package.json ./
COPY packages/ui/package.json ./packages/ui/
COPY web/package.json ./web/

RUN npm install

WORKDIR /repo/web
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
